<?php

namespace BCL\UserBundle\Repository;

/**
 * SchoolyearRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolyearRepository extends \Doctrine\ORM\EntityRepository
{
}
