bcl_user_homepage:
    path:     /
    defaults: { _controller: BCLUserBundle:User:index }

bcl_user_remove:
    path:     /remove/{id}
    defaults: { _controller: BCLUserBundle:User:removeUser }
    requirements:
        id: \d+

bcl_user_signIn:
    path:     /signIn
    defaults: { _controller: BCLUserBundle:User:signIn }

bcl_user_logIn:
    path:     /logIn
    defaults: { _controller: BCLUserBundle:User:logIn }

bcl_user_logOut:
    path:     /logOut
    defaults: { _controller: BCLUserBundle:User:logOut }

bcl_user_profil:
    path:     /profil/{id}
    defaults: { _controller: BCLUserBundle:User:viewProfil }
    requirements:
            id: \d+