bcl_activity_homepage:
    path:     /
    defaults: { _controller: BCLActivityBundle:Activity:index }

bcl_activity_futuractivities:
    path:     /futureActivities/{page}
    defaults: { _controller: BCLActivityBundle:Activity:showAllFutureActivities, page: 1 }
    requirements:
        page: \d*

bcl_activity_futuractivity:
    path:     /futureActivity/{id}
    defaults: { _controller: BCLActivityBundle:Activity:showFutureActivity }
    requirements:
        id: \d*

bcl_activity_pastActivities:
    path:     /pastActivities/{page}
    defaults: { _controller: BCLActivityBundle:Activity:showAllPastActivities, page: 1 }
    requirements:
      page: \d*




bcl_activity_pastActivity:
    path:     /pastActivity/{id}/image/{id2}
    defaults: { _controller: BCLActivityBundle:Activity:showPastActivity ,id2: 1}
    requirements:
        id: \d*

bcl_activity_proposals:
    path:     /proposals/{page}
    defaults: { _controller: BCLActivityBundle:Activity:showAllProposals, page: 1 }
    requirements:
        page: \d*

bcl_activity_proposal:
    path:     /proposal/{id}
    defaults: { _controller: BCLActivityBundle:Activity:showProposal }
    requirements:
        id: \d*
