bcl_core_homepage:
    path:     /
    defaults: { _controller: BCLCoreBundle:Core:index }

bcl_core_homepage2:
    path:     /home
    defaults: { _controller: BCLCoreBundle:Core:index }

bcl_core_legalNotices:
    path:     /legalNotices
    defaults: {_controller: BCLCoreBundle:Core:legalNotices}

bcl_core_contact:
    path:     /contact
    defaults:  { _controller: BCLCoreBundle:Core:contact}
    requirements:
        _method: POST

bcl_core_bdeMembers:
    path:     /bdeMembers
    defaults: { _controller: BCLCoreBundle:Core:bdeMembers}