bcl_core_homepage:
    path:     /
    defaults: { _controller: BCLCoreBundle:Core:index }

bcl_core_homepage2:
    path:     /home
    defaults: { _controller: BCLCoreBundle:Core:index }

bcl_core_legalNotices:
    path:     /legalNotices
    defaults: {_controller: BCLCoreBundle:Core:legalNotices}
