bcl_core:
    resource: "@BCLCoreBundle/Resources/config/routing.yml"
    prefix:   /

bcl_user:
    resource: "@BCLUserBundle/Resources/config/routing.yml"
    prefix:   /user

bcl_shop:
    resource: "@BCLShopBundle/Resources/config/routing.yml"
    prefix:   /shop

bcl_activity:
    resource: "@BCLActivityBundle/Resources/config/routing.yml"
    prefix:   /activity

