<?php

namespace BCL\ActivityBundle\Repository;

/**
 * ActivityIdeaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use Doctrine\ORM\Tools\Pagination\Paginator;

class ActivityIdeaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllProposals($page,$nbPerPage)
    {
        $query = $this->createQueryBuilder('a')
            ->leftJoin('a.userCreator ','s')
            ->addSelect('s')
            ->getQuery();
        $query
            ->setFirstResult(($page-1) * $nbPerPage)
            ->setMaxResults($nbPerPage);


        return new Paginator($query,true);
    }
}
