<?php

namespace BCL\ActivityBundle\Repository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;
use Doctrine\ORM\Tools\Pagination\Paginator;

class ActivityRepository extends EntityRepository
{
    public function findAllActivities($status,$page,$nbPerPage)
    {
        $query = $this->createQueryBuilder('a')
            ->leftJoin('a.activityStatus ','s')
            ->addSelect('s')
            ->where('s.nameStatus = :status')
            ->setParameter('status', $status)
            ->getQuery();
        $query
            ->setFirstResult(($page-1) * $nbPerPage)
            ->setMaxResults($nbPerPage);


        return new Paginator($query,true);
    }
}
