<?php

namespace BCL\ActivityBundle\Repository;

/**
 * ActivityDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityDateRepository extends \Doctrine\ORM\EntityRepository
{
}
