<?php

namespace BCL\ActivityBundle\Repository;

/**
 * ActivityStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
