<?php

namespace BCL\ActivityBundle\Repository;

/**
 * ActivityIdeaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityIdeaRepository extends \Doctrine\ORM\EntityRepository
{
}
