<?php

namespace BCL\ActivityBundle\Repository;

/**
 * Picture_GalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Picture_GalleryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllPicture($gallery)
    {
        $query = $this->createQueryBuilder('a')
            ->leftJoin('a.gallery ','s')
            ->addSelect('s')
            ->where('a.gallery = :gallery')
            ->setParameter('gallery', $gallery)
            ->getQuery();
        return $query
            ->getResult();
    }
}
