<?php

namespace BCL\ActivityBundle\Repository;

/**
 * Picture_GalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Picture_GalleryRepository extends \Doctrine\ORM\EntityRepository
{
}
