<?php

namespace BCL\ActivityBundle\Repository;

/**
 * PictureCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PictureCommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllComment($picture)
    {
        $query = $this->createQueryBuilder('a')
            ->leftJoin('a.imageCommented ','s')
            ->addSelect('s')
            ->leftJoin('a.userCommented ','u')
            ->addSelect('u')
            ->where('a.imageCommented = :picture')
            ->setParameter('picture', $picture)
            ->getQuery();
        return $query
            ->getResult();
    }
}
