<?php

namespace BCL\ShopBundle\Repository;

/**
 * To_ComposeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class To_ComposeRepository extends \Doctrine\ORM\EntityRepository
{
}
